### PR TITLE
Update tool HESS to 0.0.2+galaxy0

### PR DESCRIPTION
**Pull request by dsavchenko**

### CODE REVIEW

**Comment by volodymyrss** [comment]
Need to clean-up. This also offers a fix for showing image with aladinlite (https://github.com/cds-astro/aladin-lite/issues/136)

**Comment by dsavchenko** [comment]
Also added here an action to cleanup live preview on PR merge/closing/unlabeling

**Comment by dsavchenko** [comment]
@volodymyrss I think it's ready, could you accept?
New PRs would be by the bot

**Review by volodymyrss — APPROVED** [review]

**Comment by volodymyrss** [comment]
@andriineronov should we put this in prod in MMODA?

**Comment by andriineronov** [comment]
Yes, main instance of MMODA and Galaxy?

**Pull request merged**
